apiVersion: v1
kind: Service
metadata:
  name: eth-miner-p2p-udp
  namespace: default
  labels:
    app: geth
    type: ropsten-miner
spec:
  type: LoadBalancer
  loadBalancerIP: 35.238.26.96
  ports:
  - name: udp-p2p-30303
    port: 30303
    targetPort: 30303
    protocol: UDP
  selector:
    app: geth
    type: ropsten-miner
