apiVersion: v1
kind: Service
metadata:
  name: ropsten-miner-rpc-ws
  namespace: default
  labels:
    app: geth
    type: ropsten-miner
spec:
  ports:
  - name: tcp-rpc-8545
    port: 8545
    targetPort: 8545
  - name: tcp-ws-8546
    port: 8546
    targetPort: 8546
  selector:
    app: geth
    type: ropsten-miner
