apiVersion: v1
kind: Service
metadata:
  name: ropsten-miner-p2p-tcp
  namespace: default
  labels:
    app: geth
    type: ropsten-miner
spec:
  type: LoadBalancer
  loadBalancerIP: 35.238.26.96
  ports:
  - name: tcp-p2p-30303
    port: 30303
    targetPort: 30303
  selector:
    app: geth
    type: ropsten-miner
