---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: keep-network-relay-request-submitter
  namespace: default
  labels:
    app: keep-network
    type: relay-requester
spec:
  schedule: '*/10 * * * *'
  jobTemplate:
    metadata:
      labels:
        app: keep-network
        type: relay-requester
    spec:
      activeDeadlineSeconds: 600
      template:
        spec:
          volumes:
          - name: relay-requester-config
            persistentVolumeClaim:
              claimName: relay-requester-config
          - name: eth-account-keyfile
            configMap:
              name: eth-account-info
              items:
                - key: relay-requester-keyfile
                  path: relay-requester-keyfile
          restartPolicy: OnFailure

          containers:
          - name: keep-network-relay-request-submitter
            image: gcr.io/keep-test-f3e0/keep-client
            ports:
              - containerPort: 3919
            env:
              - name: KEEP_ETHEREUM_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: eth-account-passphrases
                    key: relay-requester
              - name: LOG_LEVEL
                value: debug
            volumeMounts:
              - name: relay-requester-config
                mountPath: /mnt/keep-client/config
              - name: eth-account-keyfile
                mountPath: /mnt/keep-client/keyfile
            command: ["keep-client", "-config", "/mnt/keep-client/config/keep-client-config.toml", "relay", "request"]
          initContainers:
          - name: initcontainer-provision-keep-client
            image: gcr.io/keep-test-f3e0/initcontainer-provision-keep-client
            imagePullPolicy: Always
            env:
              - name: KEEP_CLIENT_TYPE
                value: relay-requester
              - name: ETH_RPC_URL
                valueFrom:
                  secretKeyRef:
                    name: eth-network-ropsten
                    key: rpc-url
              - name: ETH_WS_URL
                valueFrom:
                  secretKeyRef:
                    name: eth-network-ropsten
                    key: ws-url
              - name: ETH_NETWORK_ID
                valueFrom:
                  configMapKeyRef:
                    name: eth-network-ropsten
                    key: network-id
              - name: CONTRACT_OWNER_ETH_ACCOUNT_ADDRESS
                valueFrom:
                  configMapKeyRef:
                    name: eth-network-ropsten
                    key: contract-owner-eth-account-address
              - name: CONTRACT_OWNER_ETH_ACCOUNT_PRIVATE_KEY
                valueFrom:
                  secretKeyRef:
                    name: eth-network-ropsten
                    key: contract-owner-eth-account-private-key
              - name: KEEP_CLIENT_ETH_KEYFILE_PATH
                value: /mnt/keep-client/keyfile/relay-requester-keyfile
              - name: KEEP_CLIENT_PORT
                value: '3919'
              - name: KEEP_CLIENT_DATA_DIR
                value: /mnt/keep-client/data
            volumeMounts:
              - name: relay-requester-config
                mountPath: /mnt/keep-client/config
              - name: eth-account-keyfile
                mountPath: /mnt/keep-client/keyfile
            command: ["node", "/tmp/provision-keep-client.js"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: relay-requester-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi

